In [70]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score 
from sklearn.metrics import roc_auc_score
from sklearn import metrics
from sklearn import linear_model, tree, ensemble
from sklearn.model_selection import cross_validate
%matplotlib inline

In [71]:
Dataset = 'FinalCompleteDatasetwithLocationUpdated.csv'
df = pd.read_csv(Dataset)

In [72]:
df.head()

,Location,Region,SnowDepth,Class,X,Y,Coordinates,Snowvolume,Snowweight,AveMaxpressure,AveMinpressure,Ave. Mean pressure,AvergaeTempnearSurface,RHumidity,MinAmplitudeSound(Db),MaxAmplitudeSound(Db),MeanAmplitude(DB)
0,1,SR1,30,4,65.061403,25.479150,"65.061403475,25.4791502965053",9702.60,435,22.77,1.86,3.310000,15.430000,11.503333,47.309760,51.293321,48.464098
1,2,SR1,35,5,65.061446,25.478976,"65.061446009,25.4789757112956",11319.70,618,24.34,1.40,5.287727,15.590909,11.040909,46.020600,49.187850,48.135447
2,3,SR1,39,6,65.061393,25.479098,"65.0613925,25.4790982528733",12613.38,752,11.35,0.55,6.089000,15.716667,10.053333,45.436832,51.126050,48.047521
3,4,SR1,17,2,65.061397,25.479207,"65.0613972,25.4792070106939",5498.14,325,26.12,2.00,3.030000,17.200000,8.485417,47.857601,54.469113,47.857601
4,5,SR1,13,1,65.061179,25.479134,"65.06117902006007, 25.479133551302514",4204.46,250,41.22,3.89,10.802500,15.700000,16.425000,44.454329,50.906142,48.351279

In [73]:
Zone1 = df[df['Region'] == 'SR1']
Zone2 = df[df['Region'] == 'SR2']
Zone3 = df[df['Region'] == 'SR3']
Zone4 = df[df['Region'] == 'SR4']

In [74]:
Zone1.head()

,Location,Region,SnowDepth,Class,X,Y,Coordinates,Snowvolume,Snowweight,AveMaxpressure,AveMinpressure,Ave. Mean pressure,AvergaeTempnearSurface,RHumidity,MinAmplitudeSound(Db),MaxAmplitudeSound(Db),MeanAmplitude(DB)
0,1,SR1,30,4,65.061403,25.479150,"65.061403475,25.4791502965053",9702.60,435,22.77,1.86,3.310000,15.430000,11.503333,47.309760,51.293321,48.464098
1,2,SR1,35,5,65.061446,25.478976,"65.061446009,25.4789757112956",11319.70,618,24.34,1.40,5.287727,15.590909,11.040909,46.020600,49.187850,48.135447
2,3,SR1,39,6,65.061393,25.479098,"65.0613925,25.4790982528733",12613.38,752,11.35,0.55,6.089000,15.716667,10.053333,45.436832,51.126050,48.047521
3,4,SR1,17,2,65.061397,25.479207,"65.0613972,25.4792070106939",5498.14,325,26.12,2.00,3.030000,17.200000,8.485417,47.857601,54.469113,47.857601
4,5,SR1,13,1,65.061179,25.479134,"65.06117902006007, 25.479133551302514",4204.46,250,41.22,3.89,10.802500,15.700000,16.425000,44.454329,50.906142,48.351279

In [75]:
Zone1

,Location,Region,SnowDepth,Class,X,Y,Coordinates,Snowvolume,Snowweight,AveMaxpressure,AveMinpressure,Ave. Mean pressure,AvergaeTempnearSurface,RHumidity,MinAmplitudeSound(Db),MaxAmplitudeSound(Db),MeanAmplitude(DB)
0,1,SR1,30,4,65.061403,25.479150,"65.061403475,25.4791502965053",9702.60,435,22.77,1.86,3.310000,15.430000,11.503333,47.309760,51.293321,48.464098
1,2,SR1,35,5,65.061446,25.478976,"65.061446009,25.4789757112956",11319.70,618,24.34,1.40,5.287727,15.590909,11.040909,46.020600,49.187850,48.135447
2,3,SR1,39,6,65.061393,25.479098,"65.0613925,25.4790982528733",12613.38,752,11.35,0.55,6.089000,15.716667,10.053333,45.436832,51.126050,48.047521
3,4,SR1,17,2,65.061397,25.479207,"65.0613972,25.4792070106939",5498.14,325,26.12,2.00,3.030000,17.200000,8.485417,47.857601,54.469113,47.857601
4,5,SR1,13,1,65.061179,25.479134,"65.06117902006007, 25.479133551302514",4204.46,250,41.22,3.89,10.802500,15.700000,16.425000,44.454329,50.906142,48.351279
5,6,SR1,37,6,65.061183,25.479197,"65.06118264662899, 25.47919702672048",11966.54,721,12.97,0.58,3.774800,16.603846,9.434615,46.361267,54.202347,48.922041
6,7,SR1,40,6,65.061462,25.479423,"65.0614621119724, 25.479423428968232",12936.80,896,14.01,0.65,8.361364,16.836364,8.781818,45.529236,51.618500,48.650640
7,8,SR1,27,4,65.061412,25.479359,"65.06141226187184, 25.479358777658717",8732.34,515,26.96,1.89,5.236786,16.658824,17.286275,44.810985,49.307657,48.323297
8,9,SR1,28,4,65.061370,25.479375,"65.06137021161558, 25.47937497785805",9055.76,548,25.84,1.92,7.361613,33.190698,8.004651,47.309760,49.066367,48.957055
9,10,SR1,27,4,65.061286,25.479364,"65.06128608703816, 25.479364169582766",8732.34,515,26.96,1.89,5.236786,16.658824,17.286275,44.810985,49.307657,48.323297
10,11,SR1,13,1,65.061235,25.479351,"65.06123502780261, 25.479350720983945",4204.46,250,41.22,3.89,10.802500,15.700000,16.425000,44.454329,50.906142,48.351279
11,12,SR1,22,3,65.061181,25.479356,"65.06118062935879, 25.479356136454584",7115.24,525,27.31,2.87,8.450345,14.106667,6.026667,43.287057,50.474929,48.957055
12,13,SR1,28,4,65.060880,25.479349,"65.06088036759479, 25.479349406818162",9055.76,548,25.84,1.92,7.361613,33.190698,8.004651,47.309760,49.066367,48.957055
13,14,SR1,19,2,65.061061,25.479982,"65.0610608614372, 25.479982106120815",6144.98,360,28.53,2.40,4.481875,14.368750,13.818750,48.366026,52.908445,48.339048
14,15,SR1,24,3,65.060895,25.479691,"65.06089455163396, 25.47969062144574",7762.08,405,22.23,2.01,2.985833,17.322222,8.288889,45.800692,50.705882,48.088121
15,16,SR1,15,1,65.060895,25.479691,"65.06089455163396, 25.47969062144574",4851.30,302,34.50,3.50,6.519474,16.034211,16.734211,43.806634,50.578334,48.367771
16,17,SR1,27,4,65.060819,25.479706,"65.0608189387844, 25.47970615993251",8732.34,515,26.96,1.89,5.236786,16.658824,17.286275,44.810985,49.307657,48.323297
17,18,SR1,25,3,65.060873,25.479519,"65.06087326364022, 25.479518593947343",8085.50,518,25.84,2.78,6.931923,14.611538,14.619231,47.309760,49.035729,48.456088
18,19,SR1,26,4,65.060799,25.479428,"65.06079889366085, 25.47942765974321",8408.92,634,25.84,2.78,7.361613,14.606250,14.590625,47.309760,49.066367,48.346755
19,20,SR1,35,5,65.061172,25.480053,"65.06117197777213, 25.480052543012814",11319.70,743,17.92,0.86,4.113810,31.468182,9.750000,47.747797,54.599486,49.505120
20,21,SR1,15,1,65.061204,25.480155,"65.06120378481036, 25.48015492116104",4851.30,493,33.30,2.95,4.877250,11.997561,8.878049,47.853939,49.993742,49.202164
21,22,SR1,14,1,65.061206,25.480209,"65.061206057817, 25.480208797773376",4527.88,501,36.30,3.12,4.354815,33.190698,8.004651,48.198662,49.827234,49.293323
22,23,SR1,32,5,65.061129,25.480138,"65.06112893040091, 25.48013839560163",10349.44,565,19.69,1.36,4.075714,14.475000,14.303571,47.120517,49.855208,48.361289
23,24,SR1,17,2,65.061138,25.480241,"65.06113800112583, 25.48024076627798",5498.14,476,34.50,2.84,5.957143,9.941379,16.355172,47.604225,52.485642,49.131658
24,25,SR1,33,5,65.060799,25.479428,"65.06079889366085, 25.47942765974321",10672.86,328,23.43,2.45,7.102500,24.156000,16.796000,47.676307,51.434177,49.608523

In [86]:
X = Zone1[['AveMaxpressure','AveMinpressure']]
#Zone1.drop(['Location','Region', 'SnowDepth', 'Class','X','Y','Coordinates','Snowvolume','Snowweight'], axis = 1)

In [87]:
X

    AveMaxpressure  AveMinpressure
0            22.77            1.86
1            24.34            1.40
2            11.35            0.55
3            26.12            2.00
4            41.22            3.89
5            12.97            0.58
6            14.01            0.65
7            26.96            1.89
8            25.84            1.92
9            26.96            1.89
10           41.22            3.89
11           27.31            2.87
12           25.84            1.92
13           28.53            2.40
14           22.23            2.01
15           34.50            3.50
16           26.96            1.89
17           25.84            2.78
18           25.84            2.78
19           17.92            0.86
20           33.30            2.95
21           36.30            3.12
22           19.69            1.36
23           34.50            2.84
24           23.43            2.45

In [88]:
y = Zone1['Class']

In [89]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [90]:
from sklearn.ensemble import RandomForestClassifier

# instantiate the classifier 

rfc = RandomForestClassifier(random_state=42)

# fit the model

rfc.fit(X_train, y_train)

# Predict the Test set results

y_pred = rfc.predict(X_test)

# Check accuracy score 

from sklearn.metrics import accuracy_score

print('Model accuracy score with 10 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with 10 decision-trees : 0.4000

<h1> Zone 2 prediction accuracy </h1>

In [81]:
X2 = Zone2.drop(['Location','Region', 'SnowDepth', 'Class','X','Y','Coordinates','Snowvolume','Snowweight'], axis = 1)
y2 = Zone2['Class']


X_train, X_test, y_train, y_test = train_test_split(X2, y2, test_size = 0.20, random_state = 42)
rfc = RandomForestClassifier(random_state=42)

# fit the model

rfc.fit(X_train, y_train)

# Predict the Test set results

y_pred = rfc.predict(X_test)

# Check accuracy score 

from sklearn.metrics import accuracy_score

print('Model accuracy score with 10 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with 10 decision-trees : 0.4000

In [82]:
X3 = Zone3.drop(['Location','Region', 'SnowDepth', 'Class','X','Y','Coordinates','Snowvolume','Snowweight'], axis = 1)
y3 = Zone3['Class']


X_train, X_test, y_train, y_test = train_test_split(X3, y3, test_size = 0.20, random_state = 42)
rfc = RandomForestClassifier(random_state=42)

# fit the model

rfc.fit(X_train, y_train)

# Predict the Test set results

y_pred = rfc.predict(X_test)

# Check accuracy score 

from sklearn.metrics import accuracy_score

print('Model accuracy score with 10 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with 10 decision-trees : 0.2500

In [83]:
X4 = Zone4.drop(['Location','Region', 'SnowDepth', 'Class','X','Y','Coordinates','Snowvolume','Snowweight'], axis = 1)
y4 = Zone4['Class']


X_train, X_test, y_train, y_test = train_test_split(X4, y4, test_size = 0.20, random_state = 42)
rfc = RandomForestClassifier(random_state=42)

# fit the model

rfc.fit(X_train, y_train)

# Predict the Test set results

y_pred = rfc.predict(X_test)

# Check accuracy score 

from sklearn.metrics import accuracy_score

print('Model accuracy score with 10 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score with 10 decision-trees : 0.5000